coverage:
  status:
    project:
      default:
        target: auto # Auto-adjusts based on previous coverage
        threshold: 1% # Allows up to a 1% drop without failing
    patch:
      default:
        target: auto # or you can set a specific target like 80%
        threshold: 5% # Allows coverage to be up to 5% below the target