name: manifest_dart_sdk
description: The 1-file micro-backend
version: 0.1.0
homepage: https://zoocityboy.github.io/
documentation: https://pub.dev/documentation/manifest_dart_sdk/latest/
repository: https://github.com/zoocityboy/manifest-dart-sdk
issue_tracker: https://github.com/zoocityboy/manifest-dart-sdk/issues
topics:
  - android
  - dontkillmyapp
  - doki

environment:
  sdk: ">=3.7.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  http: ^1.4.0
  http_parser: ^4.0.2
  logging: ^1.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
