name: manifest_dart_sdk
description: A Dart SDK for Manifest - a lightweight micro-backend solution with minimal dependencies
version: 0.1.2+1
homepage: https://zoocityboy.github.io/
documentation: https://pub.dev/documentation/manifest_dart_sdk/latest/
repository: https://github.com/zoocityboy/manifest-dart-sdk
issue_tracker: https://github.com/zoocityboy/manifest-dart-sdk/issues
topics:
  - manifest
  - dart-sdk
  - micro-backend

# This package is compatible with Dart's WebAssembly (WASM) target.
# No dart:io dependencies are used; all HTTP operations use the 'http' package.

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  http: ^1.4.0
  http_parser: ^4.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
