# Workflow for publishing to pub.dev using pub workspaces
name: Release to pub.dev

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Publish to pub.dev
        run: echo "${{ env.PUB_DEV_CREDENTIALS }}" > ~/.pub-cache/credentials.json && dart pub publish --force
        env:
          PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
